#!/bin/bash
#SBATCH -N 1
#SBATCH -n 8
#SBATCH --gres=gpu:1
#SBATCH --time=05:30:00
export THEANO_FLAGS="device=gpu"
source ~/.myworkrc
source activate py3
source ~/.cudarc_new
python --version
nvcc --version
dev=$(nvidia-smi |grep 0MiB -B1|awk '{print $2}'|head -n 1)
ARGV='--batchSize=32 --classifier=alexnet --dataroot=/home/mcherti/work/data/coco --imageSize=64 --nz=4096 --niter=10'
CUDA_VISIBLE_DEVICES=$dev codeopt --folder-prefix=opt --optim=maximize --argv="$ARGV" --verbose=1 ppgn.py
